<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_NB2toJD8Eeq-c7imKJrgdQ" name="1stDiagram" author="miche" bonitaVersion="7.10.4" bonitaModelVersion="7.10.0-001" configId="ACED0005740010372E31302E302D303031372E31302E34">
    <elements xmi:type="process:Pool" xmi:id="_Yui-QJD8Eeq-c7imKJrgdQ" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_Zc55EJD8Eeq-c7imKJrgdQ" name="Client lane" actor="_webaUJEEEeq2jb4JIXyuMQ">
        <elements xmi:type="process:StartEvent" xmi:id="_nFDJwJD8Eeq-c7imKJrgdQ" name="Start" outgoing="_qzkC4JD8Eeq-c7imKJrgdQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nFDJwpD8Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nFDJwZD8Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nFDJw5D8Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_pLmmkJD8Eeq-c7imKJrgdQ" name="Choose a product" outgoing="_8bTVoJD8Eeq-c7imKJrgdQ" incoming="_qzkC4JD8Eeq-c7imKJrgdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pLmmkpD8Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pLmmkZD8Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pLmmk5D8Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_IvyvYJj7EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IvyvYZj7EeqR2YN5fDIP-g" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_XkR3YJj7EeqR2YN5fDIP-g" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command">
                <defaultValue xmi:type="expression:Expression" xmi:id="_hEissJj7EeqR2YN5fDIP-g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
              </referencedElements>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IvyvYpj7EeqR2YN5fDIP-g" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_IvyvY5j7EeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setProduct">
              <inputTypes>java.util.List</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pLmmlJD8Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pLmmlZD8Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pLmmlpD8Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pLmmmJD8Eeq-c7imKJrgdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pLmml5D8Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pLmmmpD8Eeq-c7imKJrgdQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_pLmmm5D8Eeq-c7imKJrgdQ" name="ChooseProductForm" content="3b13fc1e-9089-4d24-8ff6-90d1c855a320" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pLmmmZD8Eeq-c7imKJrgdQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_pLmmnJD8Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_5GZPUJD8Eeq-c7imKJrgdQ" name="Do you have an account?" outgoing="_EMD8MJD9Eeq-c7imKJrgdQ _Ns_f4JD9Eeq-c7imKJrgdQ" incoming="_8bTVoJD8Eeq-c7imKJrgdQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5GZPUpD8Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5GZPUZD8Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5GZPU5D8Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_DQwxkJD9Eeq-c7imKJrgdQ" name="Connect yourself" outgoing="_g7c40JD9Eeq-c7imKJrgdQ" incoming="_EMD8MJD9Eeq-c7imKJrgdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DQxYoZD9Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DQxYoJD9Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DQxYopD9Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_lBd1QJj7EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_lBd1QZj7EeqR2YN5fDIP-g" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mEta8Jj7EeqR2YN5fDIP-g" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_lBd1Qpj7EeqR2YN5fDIP-g" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_lBd1Q5j7EeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setLogin">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_nfW0AJj7EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nfW0AZj7EeqR2YN5fDIP-g" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_oUlL0Jj7EeqR2YN5fDIP-g" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nfW0Apj7EeqR2YN5fDIP-g" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_nfW0A5j7EeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setPassword">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_DQxYo5D9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_DQxYpJD9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_DQxYpZD9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_DQxYp5D9Eeq-c7imKJrgdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_DQxYppD9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_DQxYqZD9Eeq-c7imKJrgdQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_DQxYqpD9Eeq-c7imKJrgdQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_DQxYqJD9Eeq-c7imKJrgdQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_DQxYq5D9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_LRefsJD9Eeq-c7imKJrgdQ" name="Create an account" outgoing="_gU2y4JD9Eeq-c7imKJrgdQ" incoming="_Ns_f4JD9Eeq-c7imKJrgdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LRfGwZD9Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LRfGwJD9Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_LRfGwpD9Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_vRUUcJj7EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_vRU7gJj7EeqR2YN5fDIP-g" name="firstname" content="firstname" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wBhCUJj7EeqR2YN5fDIP-g" name="firstname" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_vRU7gZj7EeqR2YN5fDIP-g" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_vRU7gpj7EeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setFirstname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_w6c1cJj7EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_w6c1cZj7EeqR2YN5fDIP-g" name="lastname" content="lastname" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xdkwoJj7EeqR2YN5fDIP-g" name="lastname" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_w6c1cpj7EeqR2YN5fDIP-g" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_w6c1c5j7EeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setLastname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yhmZcJj7EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yhmZcZj7EeqR2YN5fDIP-g" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zE4FoJj7EeqR2YN5fDIP-g" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yhmZcpj7EeqR2YN5fDIP-g" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_yhmZc5j7EeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setLogin">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_z6jJYJj7EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_z6jJYZj7EeqR2YN5fDIP-g" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0h7ScJj7EeqR2YN5fDIP-g" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_z6jJYpj7EeqR2YN5fDIP-g" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_z6jJY5j7EeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setPassword">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_1Xu5EJj7EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_1Xu5EZj7EeqR2YN5fDIP-g" name="email" content="email" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2OceoJj7EeqR2YN5fDIP-g" name="email" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_1Xu5Epj7EeqR2YN5fDIP-g" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_1Xu5E5j7EeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_LRfGw5D9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_LRfGxJD9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_LRfGxZD9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_LRfGx5D9Eeq-c7imKJrgdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_LRfGxpD9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_LRfGyZD9Eeq-c7imKJrgdQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_LRfGypD9Eeq-c7imKJrgdQ" name="CreateAccount" content="825e697c-913b-41e5-aad4-64766c1ee92c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_LRfGyJD9Eeq-c7imKJrgdQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_LRfGy5D9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_bgtHYJD9Eeq-c7imKJrgdQ" name="Validate the command" outgoing="_rdzqgKDmEeqzlurh4stdLQ" incoming="_gU2y4JD9Eeq-c7imKJrgdQ _g7c40JD9Eeq-c7imKJrgdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bgtucZD9Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bgtucJD9Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bgtucpD9Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_76W4kJj7EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_76W4kZj7EeqR2YN5fDIP-g" name="command_number" content="command_number" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8vS8gJj7EeqR2YN5fDIP-g" name="command_number" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command">
                <defaultValue xmi:type="expression:Expression" xmi:id="_CNgRoJj8EeqR2YN5fDIP-g" name="init_command_number()" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Command"/>
              </referencedElements>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_76W4kpj7EeqR2YN5fDIP-g" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_76W4k5j7EeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setCommand_Number">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Enb9cJj8EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Enb9cZj8EeqR2YN5fDIP-g" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FR0XMJj8EeqR2YN5fDIP-g" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command">
                <defaultValue xmi:type="expression:Expression" xmi:id="_eyweAJkAEeqR2YN5fDIP-g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
              </referencedElements>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Enb9cpj8EeqR2YN5fDIP-g" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_V4hqwJj8EeqR2YN5fDIP-g" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Enb9c5j8EeqR2YN5fDIP-g" type="ASSIGNMENT" expression="containsAll">
              <inputTypes>java.util.Collection</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IiyYsJj8EeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IiyYsZj8EeqR2YN5fDIP-g" name="price" content="price" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_OoaTIJj8EeqR2YN5fDIP-g" name="price" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IiyYspj8EeqR2YN5fDIP-g" name="price" content="price" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UD65kJj8EeqR2YN5fDIP-g" name="price" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IiyYs5j8EeqR2YN5fDIP-g" type="ASSIGNMENT" expression="setPrice">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gGKUtZkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gGKUtpkCEeqR2YN5fDIP-g" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gGKUt5kCEeqR2YN5fDIP-g" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gGKUuJkCEeqR2YN5fDIP-g" name="productInput.Product" content="productInput?.Product" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gGKUuZkCEeqR2YN5fDIP-g" name="productInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gGKUupkCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setProduct">
              <inputTypes>java.util.List</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gGKUu5kCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gGKUvJkCEeqR2YN5fDIP-g" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gGKUvZkCEeqR2YN5fDIP-g" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gGKUvpkCEeqR2YN5fDIP-g" name="productInput.Price" content="productInput?.Price" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gGKUv5kCEeqR2YN5fDIP-g" name="productInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gGKUwJkCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setPrice">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gGKUwZkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gGKUwpkCEeqR2YN5fDIP-g" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_gGKUw5kCEeqR2YN5fDIP-g" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gGKUxJkCEeqR2YN5fDIP-g" name="productInput.Command_Number" content="productInput?.Command_Number" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_gGKUxZkCEeqR2YN5fDIP-g" name="productInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_gGKUxpkCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setCommand_Number">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hM56XJkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hM56XZkCEeqR2YN5fDIP-g" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hM56XpkCEeqR2YN5fDIP-g" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hM56X5kCEeqR2YN5fDIP-g" name="loginInput.Login" content="loginInput?.Login" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hM56YJkCEeqR2YN5fDIP-g" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hM56YZkCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setLogin">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hM56YpkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hM56Y5kCEeqR2YN5fDIP-g" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hM56ZJkCEeqR2YN5fDIP-g" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hM56ZZkCEeqR2YN5fDIP-g" name="loginInput.Password" content="loginInput?.Password" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hM56ZpkCEeqR2YN5fDIP-g" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hM56Z5kCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setPassword">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hM56aJkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hM56aZkCEeqR2YN5fDIP-g" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hM56apkCEeqR2YN5fDIP-g" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hM56a5kCEeqR2YN5fDIP-g" name="loginInput.Address" content="loginInput?.Address" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hM56bJkCEeqR2YN5fDIP-g" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hM56bZkCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setAddress">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hM56bpkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hM56b5kCEeqR2YN5fDIP-g" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hM56cJkCEeqR2YN5fDIP-g" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hM56cZkCEeqR2YN5fDIP-g" name="loginInput.Firstname" content="loginInput?.Firstname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hM56cpkCEeqR2YN5fDIP-g" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hM56c5kCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setFirstname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hM56dJkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hM56dZkCEeqR2YN5fDIP-g" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hM56dpkCEeqR2YN5fDIP-g" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hM56d5kCEeqR2YN5fDIP-g" name="loginInput.Lastname" content="loginInput?.Lastname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hM56eJkCEeqR2YN5fDIP-g" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hM56eZkCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setLastname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hM56epkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hM56e5kCEeqR2YN5fDIP-g" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hM56fJkCEeqR2YN5fDIP-g" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hM56fZkCEeqR2YN5fDIP-g" name="loginInput.Email" content="loginInput?.Email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hM56fpkCEeqR2YN5fDIP-g" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hM56f5kCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hzQIrJkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hzQIrZkCEeqR2YN5fDIP-g" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hzQIrpkCEeqR2YN5fDIP-g" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hzQIr5kCEeqR2YN5fDIP-g" name="passwordInput.Login" content="passwordInput?.Login" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hzQIsJkCEeqR2YN5fDIP-g" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hzQIsZkCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setLogin">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hzQIspkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hzQIs5kCEeqR2YN5fDIP-g" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hzQItJkCEeqR2YN5fDIP-g" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hzQItZkCEeqR2YN5fDIP-g" name="passwordInput.Password" content="passwordInput?.Password" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hzQItpkCEeqR2YN5fDIP-g" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hzQIt5kCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setPassword">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hzQIuJkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hzQIuZkCEeqR2YN5fDIP-g" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hzQIupkCEeqR2YN5fDIP-g" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hzQIu5kCEeqR2YN5fDIP-g" name="passwordInput.Address" content="passwordInput?.Address" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hzQIvJkCEeqR2YN5fDIP-g" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hzQIvZkCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setAddress">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hzQIvpkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hzQIv5kCEeqR2YN5fDIP-g" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hzQIwJkCEeqR2YN5fDIP-g" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hzQIwZkCEeqR2YN5fDIP-g" name="passwordInput.Firstname" content="passwordInput?.Firstname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hzQIwpkCEeqR2YN5fDIP-g" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hzQIw5kCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setFirstname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hzQIxJkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hzQIxZkCEeqR2YN5fDIP-g" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hzQIxpkCEeqR2YN5fDIP-g" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hzQIx5kCEeqR2YN5fDIP-g" name="passwordInput.Lastname" content="passwordInput?.Lastname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hzQIyJkCEeqR2YN5fDIP-g" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hzQIyZkCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setLastname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_hzQIypkCEeqR2YN5fDIP-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_hzQIy5kCEeqR2YN5fDIP-g" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hzQIzJkCEeqR2YN5fDIP-g" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_hzQIzZkCEeqR2YN5fDIP-g" name="passwordInput.Email" content="passwordInput?.Email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_hzQIzpkCEeqR2YN5fDIP-g" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_hzQIz5kCEeqR2YN5fDIP-g" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bgtuc5D9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bgtudJD9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bgtudZD9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bgtud5D9Eeq-c7imKJrgdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bgtudpD9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_bgtueZD9Eeq-c7imKJrgdQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_bgtuepD9Eeq-c7imKJrgdQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_bgtueJD9Eeq-c7imKJrgdQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_gGKUsJkCEeqR2YN5fDIP-g" name="productInput" type="COMPLEX" dataReference="product" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_gGKUsZkCEeqR2YN5fDIP-g" name="Product" multiple="true" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_gGKUspkCEeqR2YN5fDIP-g" name="Price" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_gGKUs5kCEeqR2YN5fDIP-g" name="Command_Number" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_hM56UJkCEeqR2YN5fDIP-g" name="loginInput" type="COMPLEX" dataReference="login" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_hM56UZkCEeqR2YN5fDIP-g" name="Login" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_hM56UpkCEeqR2YN5fDIP-g" name="Password" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_hM56U5kCEeqR2YN5fDIP-g" name="Address" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_hM56VJkCEeqR2YN5fDIP-g" name="Firstname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_hM56VZkCEeqR2YN5fDIP-g" name="Lastname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_hM56VpkCEeqR2YN5fDIP-g" name="Email" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_hzQIoJkCEeqR2YN5fDIP-g" name="passwordInput" type="COMPLEX" dataReference="password" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_hzQIoZkCEeqR2YN5fDIP-g" name="Login" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_hzQIopkCEeqR2YN5fDIP-g" name="Password" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_hzQIo5kCEeqR2YN5fDIP-g" name="Address" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_hzQIpJkCEeqR2YN5fDIP-g" name="Firstname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_hzQIpZkCEeqR2YN5fDIP-g" name="Lastname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_hzQIppkCEeqR2YN5fDIP-g" name="Email" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_hzQIp5kCEeqR2YN5fDIP-g" expression="passwordInput?.Login != null" errorMessage="Login is mandatory for Customer" name="mandatory_passwordInput_Login">
              <inputNames>passwordInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_hzQIqJkCEeqR2YN5fDIP-g" expression="passwordInput?.Password != null" errorMessage="Password is mandatory for Customer" name="mandatory_passwordInput_Password">
              <inputNames>passwordInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_hzQIqZkCEeqR2YN5fDIP-g" expression="passwordInput?.Address != null" errorMessage="Address is mandatory for Customer" name="mandatory_passwordInput_Address">
              <inputNames>passwordInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_hzQIqpkCEeqR2YN5fDIP-g" expression="passwordInput?.Firstname != null" errorMessage="Firstname is mandatory for Customer" name="mandatory_passwordInput_Firstname">
              <inputNames>passwordInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_hzQIq5kCEeqR2YN5fDIP-g" expression="passwordInput?.Lastname != null" errorMessage="Lastname is mandatory for Customer" name="mandatory_passwordInput_Lastname">
              <inputNames>passwordInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_bgtue5D9Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_viaswJD-Eeq-c7imKJrgdQ" name="Receive the product" outgoing="_AWFeQJD_Eeq-c7imKJrgdQ" incoming="_0FAuMJD-Eeq-c7imKJrgdQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vibT0ZD-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vibT0JD-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vibT0pD-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_vibT05D-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_vibT1JD-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_vibT1ZD-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_vibT15D-Eeq-c7imKJrgdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_vibT1pD-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_61pUgJD-Eeq-c7imKJrgdQ" name="Do you want to make a review?" outgoing="_IYE-wJD_Eeq-c7imKJrgdQ _Ckt5AJD_Eeq-c7imKJrgdQ" incoming="_AWFeQJD_Eeq-c7imKJrgdQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_61pUgpD-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_61pUgZD-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_61pUg5D-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BkYdYJD_Eeq-c7imKJrgdQ" name="Make a review" outgoing="_Qp_IEKD5Eeqfyd2IOtaQOQ" incoming="_Ckt5AJD_Eeq-c7imKJrgdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BkYdYpD_Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BkYdYZD_Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BkYdY5D_Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_UIZqXKDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UIZqXaDmEeqzlurh4stdLQ" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UIZqXqDmEeqzlurh4stdLQ" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UIZqX6DmEeqzlurh4stdLQ" name="passwordInput.Login" content="passwordInput?.Login" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UIZqYKDmEeqzlurh4stdLQ" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UIZqYaDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setLogin">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_UIZqYqDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UIZqY6DmEeqzlurh4stdLQ" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UIZqZKDmEeqzlurh4stdLQ" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UIZqZaDmEeqzlurh4stdLQ" name="passwordInput.Password" content="passwordInput?.Password" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UIZqZqDmEeqzlurh4stdLQ" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UIZqZ6DmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setPassword">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_UIZqaKDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UIZqaaDmEeqzlurh4stdLQ" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UIZqaqDmEeqzlurh4stdLQ" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UIZqa6DmEeqzlurh4stdLQ" name="passwordInput.Address" content="passwordInput?.Address" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UIZqbKDmEeqzlurh4stdLQ" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UIZqbaDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setAddress">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_UIZqbqDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UIZqb6DmEeqzlurh4stdLQ" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UIZqcKDmEeqzlurh4stdLQ" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UIZqcaDmEeqzlurh4stdLQ" name="passwordInput.Firstname" content="passwordInput?.Firstname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UIZqcqDmEeqzlurh4stdLQ" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UIZqc6DmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setFirstname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_UIZqdKDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UIZqdaDmEeqzlurh4stdLQ" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UIZqdqDmEeqzlurh4stdLQ" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UIZqd6DmEeqzlurh4stdLQ" name="passwordInput.Lastname" content="passwordInput?.Lastname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UIZqeKDmEeqzlurh4stdLQ" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UIZqeaDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setLastname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_UIZqeqDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UIZqe6DmEeqzlurh4stdLQ" name="password" content="password" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UIZqfKDmEeqzlurh4stdLQ" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UIZqfaDmEeqzlurh4stdLQ" name="passwordInput.Email" content="passwordInput?.Email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UIZqfqDmEeqzlurh4stdLQ" name="passwordInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UIZqf6DmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Vr8gvKDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vr8gvaDmEeqzlurh4stdLQ" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vr8gvqDmEeqzlurh4stdLQ" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vr8gv6DmEeqzlurh4stdLQ" name="loginInput.Login" content="loginInput?.Login" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vr8gwKDmEeqzlurh4stdLQ" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vr8gwaDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setLogin">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Vr8gwqDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vr8gw6DmEeqzlurh4stdLQ" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vr8gxKDmEeqzlurh4stdLQ" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vr8gxaDmEeqzlurh4stdLQ" name="loginInput.Password" content="loginInput?.Password" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vr8gxqDmEeqzlurh4stdLQ" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vr8gx6DmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setPassword">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Vr8gyKDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vr8gyaDmEeqzlurh4stdLQ" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vr8gyqDmEeqzlurh4stdLQ" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vr8gy6DmEeqzlurh4stdLQ" name="loginInput.Address" content="loginInput?.Address" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vr8gzKDmEeqzlurh4stdLQ" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vr8gzaDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setAddress">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Vr8gzqDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vr8gz6DmEeqzlurh4stdLQ" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vr8g0KDmEeqzlurh4stdLQ" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vr8g0aDmEeqzlurh4stdLQ" name="loginInput.Firstname" content="loginInput?.Firstname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vr8g0qDmEeqzlurh4stdLQ" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vr8g06DmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setFirstname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Vr8g1KDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vr8g1aDmEeqzlurh4stdLQ" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vr8g1qDmEeqzlurh4stdLQ" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vr8g16DmEeqzlurh4stdLQ" name="loginInput.Lastname" content="loginInput?.Lastname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vr8g2KDmEeqzlurh4stdLQ" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vr8g2aDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setLastname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Vr8g2qDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vr8g26DmEeqzlurh4stdLQ" name="login" content="login" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vr8g3KDmEeqzlurh4stdLQ" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vr8g3aDmEeqzlurh4stdLQ" name="loginInput.Email" content="loginInput?.Email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vr8g3qDmEeqzlurh4stdLQ" name="loginInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vr8g36DmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_WxLqcaDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_WxLqcqDmEeqzlurh4stdLQ" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_WxLqc6DmEeqzlurh4stdLQ" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_WxLqdKDmEeqzlurh4stdLQ" name="productInput.Product" content="productInput?.Product" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_WxLqdaDmEeqzlurh4stdLQ" name="productInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_WxLqdqDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setProduct">
              <inputTypes>java.util.List</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_WxLqd6DmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_WxLqeKDmEeqzlurh4stdLQ" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_WxLqeaDmEeqzlurh4stdLQ" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_WxLqeqDmEeqzlurh4stdLQ" name="productInput.Price" content="productInput?.Price" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_WxLqe6DmEeqzlurh4stdLQ" name="productInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_WxLqfKDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setPrice">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_WxLqfaDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_WxLqfqDmEeqzlurh4stdLQ" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_WxLqf6DmEeqzlurh4stdLQ" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_WxLqgKDmEeqzlurh4stdLQ" name="productInput.Command_Number" content="productInput?.Command_Number" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_WxLqgaDmEeqzlurh4stdLQ" name="productInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_WxLqgqDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setCommand_Number">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BkYdZJD_Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BkZEcJD_Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BkZEcZD_Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BkZEc5D_Eeq-c7imKJrgdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BkZEcpD_Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_BkZEdZD_Eeq-c7imKJrgdQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_BkZEdpD_Eeq-c7imKJrgdQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_BkZEdJD_Eeq-c7imKJrgdQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_UIZqUKDmEeqzlurh4stdLQ" name="passwordInput" type="COMPLEX" dataReference="password" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_UIZqUaDmEeqzlurh4stdLQ" name="Login" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_UIZqUqDmEeqzlurh4stdLQ" name="Password" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_UIZqU6DmEeqzlurh4stdLQ" name="Address" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_UIZqVKDmEeqzlurh4stdLQ" name="Firstname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_UIZqVaDmEeqzlurh4stdLQ" name="Lastname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_UIZqVqDmEeqzlurh4stdLQ" name="Email" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_Vr8gsKDmEeqzlurh4stdLQ" name="loginInput" type="COMPLEX" dataReference="login" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_Vr8gsaDmEeqzlurh4stdLQ" name="Login" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Vr8gsqDmEeqzlurh4stdLQ" name="Password" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Vr8gs6DmEeqzlurh4stdLQ" name="Address" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Vr8gtKDmEeqzlurh4stdLQ" name="Firstname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Vr8gtaDmEeqzlurh4stdLQ" name="Lastname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Vr8gtqDmEeqzlurh4stdLQ" name="Email" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_WxLDYKDmEeqzlurh4stdLQ" name="productInput" type="COMPLEX" multiple="true" dataReference="product" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_WxLDYaDmEeqzlurh4stdLQ" name="Product" multiple="true" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_WxLDYqDmEeqzlurh4stdLQ" name="Price" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_WxLDY6DmEeqzlurh4stdLQ" name="Command_Number" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_WxLqcKDmEeqzlurh4stdLQ" expression="productInput?.Price != null" errorMessage="Price is mandatory for Command" name="mandatory_productInput_Price">
              <inputNames>productInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_BkZEd5D_Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_HYLoAJD_Eeq-c7imKJrgdQ" name="End" incoming="_IYE-wJD_Eeq-c7imKJrgdQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HYMPEZD_Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HYMPEJD_Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HYMPEpD_Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_QpuCUKD5Eeqfyd2IOtaQOQ" name="End1" incoming="_Qp_IEKD5Eeqfyd2IOtaQOQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QpuCUqD5Eeqfyd2IOtaQOQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QpuCUaD5Eeqfyd2IOtaQOQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QpuCU6D5Eeqfyd2IOtaQOQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_UJrV0JEFEeq2jb4JIXyuMQ" name="User who submit the command" definitionId="initiator" definitionVersion="1.0.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_UJrV0ZEFEeq2jb4JIXyuMQ" definitionId="initiator" version="1.0.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_UJrV0pEFEeq2jb4JIXyuMQ" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_UJrV05EFEeq2jb4JIXyuMQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_HFbgkJD-Eeq-c7imKJrgdQ" name="Employee lane" actor="_xi354JEEEeq2jb4JIXyuMQ">
        <elements xmi:type="process:SendTask" xmi:id="_pDe6cJD-Eeq-c7imKJrgdQ" name="Send the product" outgoing="_0FAuMJD-Eeq-c7imKJrgdQ" incoming="_uWsDgKDjEeqzlurh4stdLQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pDe6cpD-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pDe6cZD-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pDe6c5D-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pDe6dJD-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pDe6dZD-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pDe6dpD-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pDe6eJD-Eeq-c7imKJrgdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pDe6d5D-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_O7qnEKDjEeqzlurh4stdLQ" name="Gateway2" outgoing="_uWsDgKDjEeqzlurh4stdLQ" incoming="_tBDtUKDjEeqzlurh4stdLQ _tgkT0KDjEeqzlurh4stdLQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_O7wGoaDjEeqzlurh4stdLQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_O7wGoKDjEeqzlurh4stdLQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_O7wGoqDjEeqzlurh4stdLQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_oQceAKDjEeqzlurh4stdLQ" name="Gateway1" outgoing="_qLnKMKDjEeqzlurh4stdLQ _qxSqIKDjEeqzlurh4stdLQ" incoming="_rdzqgKDmEeqzlurh4stdLQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oQdFEaDjEeqzlurh4stdLQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oQdFEKDjEeqzlurh4stdLQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oQdFEqDjEeqzlurh4stdLQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_hjiUkKD4Eeqfyd2IOtaQOQ" name="Update  inventory" outgoing="_tBDtUKDjEeqzlurh4stdLQ" incoming="_qLnKMKDjEeqzlurh4stdLQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZnP18pD-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZnP18ZD-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZnP185D-Eeq-c7imKJrgdQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_EuPCZaDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_EuPCZqDmEeqzlurh4stdLQ" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_EuPCZ6DmEeqzlurh4stdLQ" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_EuPCaKDmEeqzlurh4stdLQ" name="productInput.Product" content="productInput?.Product" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_EuPCaaDmEeqzlurh4stdLQ" name="productInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_EuPCaqDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setProduct">
              <inputTypes>java.util.List</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_EuPCa6DmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_EuPCbKDmEeqzlurh4stdLQ" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_EuPCbaDmEeqzlurh4stdLQ" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_EuPCbqDmEeqzlurh4stdLQ" name="productInput.Price" content="productInput?.Price" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_EuPCb6DmEeqzlurh4stdLQ" name="productInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_EuPCcKDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setPrice">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_EuPCcaDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_EuPCcqDmEeqzlurh4stdLQ" name="product" content="product" type="TYPE_VARIABLE" returnType="com.company.model.Command">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_EuPCc6DmEeqzlurh4stdLQ" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_EuPCdKDmEeqzlurh4stdLQ" name="productInput.Command_Number" content="productInput?.Command_Number" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_EuPCdaDmEeqzlurh4stdLQ" name="productInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_EuPCdqDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setCommand_Number">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZnP19JD-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZnP19ZD-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZnP19pD-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZnP1-JD-Eeq-c7imKJrgdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZnP195D-Eeq-c7imKJrgdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_J63RUKGAEeq0NaN6XP5iqQ" name="Sending confirmation mail" outgoing="_tgkT0KDjEeqzlurh4stdLQ" incoming="_qxSqIKDjEeqzlurh4stdLQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UJAOoaDjEeqzlurh4stdLQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UJAOoqDjEeqzlurh4stdLQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UJAOo6DjEeqzlurh4stdLQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_wSPC3KDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wSPC3aDmEeqzlurh4stdLQ" name="address" content="address" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wSPC3qDmEeqzlurh4stdLQ" name="address" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wSPC36DmEeqzlurh4stdLQ" name="addressInput.Login" content="     ?.Login" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_wSPC4aDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setLogin">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wSPC4qDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wSPC46DmEeqzlurh4stdLQ" name="address" content="address" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wSPC5KDmEeqzlurh4stdLQ" name="address" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wSPC5aDmEeqzlurh4stdLQ" name="addressInput.Password" content="     ?.Password" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_wSPC56DmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setPassword">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wSPC6KDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wSPC6aDmEeqzlurh4stdLQ" name="address" content="address" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wSPC6qDmEeqzlurh4stdLQ" name="address" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wSPC66DmEeqzlurh4stdLQ" name="addressInput.Address" content="     ?.Address" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_wSPC7aDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setAddress">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wSPC7qDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wSPC76DmEeqzlurh4stdLQ" name="address" content="address" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wSPC8KDmEeqzlurh4stdLQ" name="address" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wSPC8aDmEeqzlurh4stdLQ" name="addressInput.Firstname" content="     ?.Firstname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_wSPC86DmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setFirstname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wSPC9KDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wSPC9aDmEeqzlurh4stdLQ" name="address" content="address" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wSPC9qDmEeqzlurh4stdLQ" name="address" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wSPC96DmEeqzlurh4stdLQ" name="addressInput.Lastname" content="     ?.Lastname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_wSPC-aDmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setLastname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wSPC-qDmEeqzlurh4stdLQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wSPC-6DmEeqzlurh4stdLQ" name="address" content="address" type="TYPE_VARIABLE" returnType="com.company.model.Customer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wSPC_KDmEeqzlurh4stdLQ" name="address" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wSPC_aDmEeqzlurh4stdLQ" name="addressInput.Email" content="     ?.Email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_wSPC_6DmEeqzlurh4stdLQ" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UJAOpKDjEeqzlurh4stdLQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UJAOpaDjEeqzlurh4stdLQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UJAOpqDjEeqzlurh4stdLQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UJAOp6DjEeqzlurh4stdLQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UJAOqKDjEeqzlurh4stdLQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_G3yE4Jj7EeqR2YN5fDIP-g" name="command_number" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command">
        <defaultValue xmi:type="expression:Expression" xmi:id="_G3yE4Zj7EeqR2YN5fDIP-g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_WbBJQJj7EeqR2YN5fDIP-g" name="product" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command">
        <defaultValue xmi:type="expression:Expression" xmi:id="_WbBJQZj7EeqR2YN5fDIP-g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_elnzMJj7EeqR2YN5fDIP-g" name="login" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer">
        <defaultValue xmi:type="expression:Expression" xmi:id="_elnzMZj7EeqR2YN5fDIP-g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_gZbTIJj7EeqR2YN5fDIP-g" name="password" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer">
        <defaultValue xmi:type="expression:Expression" xmi:id="_gZbTIZj7EeqR2YN5fDIP-g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_sSyGwJj7EeqR2YN5fDIP-g" name="firstname" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer">
        <defaultValue xmi:type="expression:Expression" xmi:id="_sSyGwZj7EeqR2YN5fDIP-g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_tiI10Jj7EeqR2YN5fDIP-g" name="lastname" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer">
        <defaultValue xmi:type="expression:Expression" xmi:id="_tiI10Zj7EeqR2YN5fDIP-g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_ufBU0Jj7EeqR2YN5fDIP-g" name="email" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ufBU0Zj7EeqR2YN5fDIP-g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_NSb-sJj8EeqR2YN5fDIP-g" name="price" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Command">
        <defaultValue xmi:type="expression:Expression" xmi:id="_NSb-sZj8EeqR2YN5fDIP-g" name="init_price()" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Command"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_8WJnQJj8EeqR2YN5fDIP-g" name="address" dataType="_NB3U05D8Eeq-c7imKJrgdQ" className="com.company.model.Customer">
        <defaultValue xmi:type="expression:Expression" xmi:id="_8WJnQZj8EeqR2YN5fDIP-g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_YujlX5D8Eeq-c7imKJrgdQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_YujlYJD8Eeq-c7imKJrgdQ" name="Product" content="9a97f1e5-7810-46e9-b3f0-cce97f5f4514" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_YujlYZD8Eeq-c7imKJrgdQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_YujlYpD8Eeq-c7imKJrgdQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qzkC4JD8Eeq-c7imKJrgdQ" target="_pLmmkJD8Eeq-c7imKJrgdQ" source="_nFDJwJD8Eeq-c7imKJrgdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qzkp8JD8Eeq-c7imKJrgdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_qzkp8ZD8Eeq-c7imKJrgdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8bTVoJD8Eeq-c7imKJrgdQ" target="_5GZPUJD8Eeq-c7imKJrgdQ" source="_pLmmkJD8Eeq-c7imKJrgdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8bT8sJD8Eeq-c7imKJrgdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_8bT8sZD8Eeq-c7imKJrgdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EMD8MJD9Eeq-c7imKJrgdQ" name="Yes" target="_DQwxkJD9Eeq-c7imKJrgdQ" source="_5GZPUJD8Eeq-c7imKJrgdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EMD8MZD9Eeq-c7imKJrgdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_EMD8MpD9Eeq-c7imKJrgdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ns_f4JD9Eeq-c7imKJrgdQ" name="No" target="_LRefsJD9Eeq-c7imKJrgdQ" source="_5GZPUJD8Eeq-c7imKJrgdQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ns_f4ZD9Eeq-c7imKJrgdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ns_f4pD9Eeq-c7imKJrgdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gU2y4JD9Eeq-c7imKJrgdQ" target="_bgtHYJD9Eeq-c7imKJrgdQ" source="_LRefsJD9Eeq-c7imKJrgdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gU2y4ZD9Eeq-c7imKJrgdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_gU2y4pD9Eeq-c7imKJrgdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g7c40JD9Eeq-c7imKJrgdQ" target="_bgtHYJD9Eeq-c7imKJrgdQ" source="_DQwxkJD9Eeq-c7imKJrgdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g7c40ZD9Eeq-c7imKJrgdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_g7c40pD9Eeq-c7imKJrgdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0FAuMJD-Eeq-c7imKJrgdQ" target="_viaswJD-Eeq-c7imKJrgdQ" source="_pDe6cJD-Eeq-c7imKJrgdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0FAuMZD-Eeq-c7imKJrgdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0FAuMpD-Eeq-c7imKJrgdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AWFeQJD_Eeq-c7imKJrgdQ" target="_61pUgJD-Eeq-c7imKJrgdQ" source="_viaswJD-Eeq-c7imKJrgdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AWFeQZD_Eeq-c7imKJrgdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_AWFeQpD_Eeq-c7imKJrgdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ckt5AJD_Eeq-c7imKJrgdQ" name="Yes" target="_BkYdYJD_Eeq-c7imKJrgdQ" source="_61pUgJD-Eeq-c7imKJrgdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ckt5AZD_Eeq-c7imKJrgdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ckt5ApD_Eeq-c7imKJrgdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IYE-wJD_Eeq-c7imKJrgdQ" name="No" target="_HYLoAJD_Eeq-c7imKJrgdQ" source="_61pUgJD-Eeq-c7imKJrgdQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IYFl0JD_Eeq-c7imKJrgdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_IYFl0ZD_Eeq-c7imKJrgdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qLnKMKDjEeqzlurh4stdLQ" target="_hjiUkKD4Eeqfyd2IOtaQOQ" source="_oQceAKDjEeqzlurh4stdLQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qLnxQKDjEeqzlurh4stdLQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_qLnxQaDjEeqzlurh4stdLQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qxSqIKDjEeqzlurh4stdLQ" target="_J63RUKGAEeq0NaN6XP5iqQ" source="_oQceAKDjEeqzlurh4stdLQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qxTRMKDjEeqzlurh4stdLQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_qxTRMaDjEeqzlurh4stdLQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tBDtUKDjEeqzlurh4stdLQ" target="_O7qnEKDjEeqzlurh4stdLQ" source="_hjiUkKD4Eeqfyd2IOtaQOQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tBDtUaDjEeqzlurh4stdLQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_tBDtUqDjEeqzlurh4stdLQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tgkT0KDjEeqzlurh4stdLQ" target="_O7qnEKDjEeqzlurh4stdLQ" source="_J63RUKGAEeq0NaN6XP5iqQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tgkT0aDjEeqzlurh4stdLQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_tgkT0qDjEeqzlurh4stdLQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uWsDgKDjEeqzlurh4stdLQ" target="_pDe6cJD-Eeq-c7imKJrgdQ" source="_O7qnEKDjEeqzlurh4stdLQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uWsqkKDjEeqzlurh4stdLQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_uWsqkaDjEeqzlurh4stdLQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rdzqgKDmEeqzlurh4stdLQ" target="_oQceAKDjEeqzlurh4stdLQ" source="_bgtHYJD9Eeq-c7imKJrgdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rdzqgaDmEeqzlurh4stdLQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_rdzqgqDmEeqzlurh4stdLQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Qp_IEKD5Eeqfyd2IOtaQOQ" target="_QpuCUKD5Eeqfyd2IOtaQOQ" source="_BkYdYJD_Eeq-c7imKJrgdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Qp_IEaD5Eeqfyd2IOtaQOQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Qp_IEqD5Eeqfyd2IOtaQOQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_webaUJEEEeq2jb4JIXyuMQ" name="Client" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_xi354JEEEeq2jb4JIXyuMQ" name="Employee"/>
      <contract xmi:type="process:Contract" xmi:id="_YujlY5D8Eeq-c7imKJrgdQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_YujlUJD8Eeq-c7imKJrgdQ">
        <name xmi:type="expression:Expression" xmi:id="_YujlUZD8Eeq-c7imKJrgdQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_YujlUpD8Eeq-c7imKJrgdQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_YujlU5D8Eeq-c7imKJrgdQ">
        <name xmi:type="expression:Expression" xmi:id="_YujlVJD8Eeq-c7imKJrgdQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_YujlVZD8Eeq-c7imKJrgdQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_YujlVpD8Eeq-c7imKJrgdQ">
        <name xmi:type="expression:Expression" xmi:id="_YujlV5D8Eeq-c7imKJrgdQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_YujlWJD8Eeq-c7imKJrgdQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_YujlWZD8Eeq-c7imKJrgdQ">
        <name xmi:type="expression:Expression" xmi:id="_YujlWpD8Eeq-c7imKJrgdQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_YujlW5D8Eeq-c7imKJrgdQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_YujlXJD8Eeq-c7imKJrgdQ">
        <name xmi:type="expression:Expression" xmi:id="_YujlXZD8Eeq-c7imKJrgdQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_YujlXpD8Eeq-c7imKJrgdQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_NB3Uy5D8Eeq-c7imKJrgdQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_NB3UzJD8Eeq-c7imKJrgdQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_NB3UzZD8Eeq-c7imKJrgdQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_NB3UzpD8Eeq-c7imKJrgdQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_NB3Uz5D8Eeq-c7imKJrgdQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_NB3U0JD8Eeq-c7imKJrgdQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_NB3U0ZD8Eeq-c7imKJrgdQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_NB3U0pD8Eeq-c7imKJrgdQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_NB3U05D8Eeq-c7imKJrgdQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_NB3U1JD8Eeq-c7imKJrgdQ" type="Process" element="_NB2toJD8Eeq-c7imKJrgdQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_YulagJD8Eeq-c7imKJrgdQ" type="2007" element="_Yui-QJD8Eeq-c7imKJrgdQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_YulahZD8Eeq-c7imKJrgdQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_YulahpD8Eeq-c7imKJrgdQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_Zc6gIJD8Eeq-c7imKJrgdQ" type="3007" element="_Zc55EJD8Eeq-c7imKJrgdQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_Zc6gJZD8Eeq-c7imKJrgdQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Zc6gJpD8Eeq-c7imKJrgdQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_nFDw0JD8Eeq-c7imKJrgdQ" type="3002" element="_nFDJwJD8Eeq-c7imKJrgdQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_nFEX4JD8Eeq-c7imKJrgdQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_nFEX4ZD8Eeq-c7imKJrgdQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nFDw0ZD8Eeq-c7imKJrgdQ" x="133" y="193"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pLn0sJD8Eeq-c7imKJrgdQ" type="3005" element="_pLmmkJD8Eeq-c7imKJrgdQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pLn0spD8Eeq-c7imKJrgdQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pLn0sZD8Eeq-c7imKJrgdQ" x="213" y="162" width="182" height="91"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5GZ2YJD8Eeq-c7imKJrgdQ" type="3008" element="_5GZPUJD8Eeq-c7imKJrgdQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5GZ2YpD8Eeq-c7imKJrgdQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5GZ2Y5D8Eeq-c7imKJrgdQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5GZ2YZD8Eeq-c7imKJrgdQ" x="494" y="186"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DQx_sJD9Eeq-c7imKJrgdQ" type="3005" element="_DQwxkJD9Eeq-c7imKJrgdQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_DQx_spD9Eeq-c7imKJrgdQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DQx_sZD9Eeq-c7imKJrgdQ" x="593" y="112" width="158" height="79"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_LRfGzJD9Eeq-c7imKJrgdQ" type="3005" element="_LRefsJD9Eeq-c7imKJrgdQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_LRft0JD9Eeq-c7imKJrgdQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LRfGzZD9Eeq-c7imKJrgdQ" x="593" y="236" width="163" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bgtufJD9Eeq-c7imKJrgdQ" type="3005" element="_bgtHYJD9Eeq-c7imKJrgdQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bguVgJD9Eeq-c7imKJrgdQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bgtufZD9Eeq-c7imKJrgdQ" x="916" y="190" width="177" height="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vibT2JD-Eeq-c7imKJrgdQ" type="3026" element="_viaswJD-Eeq-c7imKJrgdQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vibT2pD-Eeq-c7imKJrgdQ" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vibT2ZD-Eeq-c7imKJrgdQ" x="1581" y="199" width="141" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_61pUhJD-Eeq-c7imKJrgdQ" type="3008" element="_61pUgJD-Eeq-c7imKJrgdQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_61p7kJD-Eeq-c7imKJrgdQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_61p7kZD-Eeq-c7imKJrgdQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_61pUhZD-Eeq-c7imKJrgdQ" x="1790" y="212"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BkZEeJD_Eeq-c7imKJrgdQ" type="3005" element="_BkYdYJD_Eeq-c7imKJrgdQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BkZEepD_Eeq-c7imKJrgdQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BkZEeZD_Eeq-c7imKJrgdQ" x="1885" y="65" width="128" height="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HYMPE5D_Eeq-c7imKJrgdQ" type="3003" element="_HYLoAJD_Eeq-c7imKJrgdQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HYMPFZD_Eeq-c7imKJrgdQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HYMPFpD_Eeq-c7imKJrgdQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HYMPFJD_Eeq-c7imKJrgdQ" x="1999" y="219"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Qp3zUKD5Eeqfyd2IOtaQOQ" type="3003" element="_QpuCUKD5Eeqfyd2IOtaQOQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Qp3zUqD5Eeqfyd2IOtaQOQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Qp3zU6D5Eeqfyd2IOtaQOQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Qp3zUaD5Eeqfyd2IOtaQOQ" x="2078" y="82"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Zc6gIZD8Eeq-c7imKJrgdQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Zc6gIpD8Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Zc6gI5D8Eeq-c7imKJrgdQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Zc6gJ5D8Eeq-c7imKJrgdQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Zc6gJJD8Eeq-c7imKJrgdQ" x="58" y="10" width="2247" height="400"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_HFcHoJD-Eeq-c7imKJrgdQ" type="3007" element="_HFbgkJD-Eeq-c7imKJrgdQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_HFcHpZD-Eeq-c7imKJrgdQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_HFcHppD-Eeq-c7imKJrgdQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_pDfhgJD-Eeq-c7imKJrgdQ" type="3025" element="_pDe6cJD-Eeq-c7imKJrgdQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pDfhgpD-Eeq-c7imKJrgdQ" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pDfhgZD-Eeq-c7imKJrgdQ" x="1581" y="104" width="154" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_O753oKDjEeqzlurh4stdLQ" type="3009" element="_O7qnEKDjEeqzlurh4stdLQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_O76esKDjEeqzlurh4stdLQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_O76esaDjEeqzlurh4stdLQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_O753oaDjEeqzlurh4stdLQ" x="1448" y="121"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oQdsIKDjEeqzlurh4stdLQ" type="3009" element="_oQceAKDjEeqzlurh4stdLQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_oQdsIqDjEeqzlurh4stdLQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_oQdsI6DjEeqzlurh4stdLQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oQdsIaDjEeqzlurh4stdLQ" x="1125" y="121"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hjl--KD4Eeqfyd2IOtaQOQ" type="3027" element="_hjiUkKD4Eeqfyd2IOtaQOQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_hjl--qD4Eeqfyd2IOtaQOQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hjl--aD4Eeqfyd2IOtaQOQ" x="1201" y="26" width="166" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_J65GgKGAEeq0NaN6XP5iqQ" type="3027" element="_J63RUKGAEeq0NaN6XP5iqQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_J65GgqGAEeq0NaN6XP5iqQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_J65GgaGAEeq0NaN6XP5iqQ" x="1201" y="178" width="202" height="101"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_HFcHoZD-Eeq-c7imKJrgdQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_HFcHopD-Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_HFcHo5D-Eeq-c7imKJrgdQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_HFcHp5D-Eeq-c7imKJrgdQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HFcHpJD-Eeq-c7imKJrgdQ" x="33" y="400" width="2547" height="365"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_YulagZD8Eeq-c7imKJrgdQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_YulagpD8Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Yulag5D8Eeq-c7imKJrgdQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Yulah5D8Eeq-c7imKJrgdQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YulahJD8Eeq-c7imKJrgdQ" width="2580" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_NB3U7JD8Eeq-c7imKJrgdQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_qzkp8pD8Eeq-c7imKJrgdQ" type="4001" element="_qzkC4JD8Eeq-c7imKJrgdQ" source="_nFDw0JD8Eeq-c7imKJrgdQ" target="_pLn0sJD8Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qzlRAJD8Eeq-c7imKJrgdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qzlRAZD8Eeq-c7imKJrgdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qzkp85D8Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qzkp9JD8Eeq-c7imKJrgdQ" points="[0, -15, -158, -2]$[143, -13, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qznGMJD8Eeq-c7imKJrgdQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qznGMZD8Eeq-c7imKJrgdQ" id="(0.15,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8bUjwJD8Eeq-c7imKJrgdQ" type="4001" element="_8bTVoJD8Eeq-c7imKJrgdQ" source="_pLn0sJD8Eeq-c7imKJrgdQ" target="_5GZ2YJD8Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8bUjw5D8Eeq-c7imKJrgdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8bUjxJD8Eeq-c7imKJrgdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8bUjwZD8Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8bUjwpD8Eeq-c7imKJrgdQ" points="[0, 13, -187, -1]$[184, 13, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8bVx4JD8Eeq-c7imKJrgdQ" id="(1.0,0.32967032967032966)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8bVx4ZD8Eeq-c7imKJrgdQ" id="(0.11627906976744186,0.46511627906976744)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EMEjQJD9Eeq-c7imKJrgdQ" type="4001" element="_EMD8MJD9Eeq-c7imKJrgdQ" source="_5GZ2YJD8Eeq-c7imKJrgdQ" target="_DQx_sJD9Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EMEjQ5D9Eeq-c7imKJrgdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EMEjRJD9Eeq-c7imKJrgdQ" x="-2" y="-13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EMEjQZD9Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EMEjQpD9Eeq-c7imKJrgdQ" points="[-24, -32, -159, 37]$[-24, -69, -159, 0]$[56, -69, -79, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EMFKUJD9Eeq-c7imKJrgdQ" id="(1.0,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NtDxUJD9Eeq-c7imKJrgdQ" type="4001" element="_Ns_f4JD9Eeq-c7imKJrgdQ" source="_5GZ2YJD8Eeq-c7imKJrgdQ" target="_LRfGzJD9Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NtDxU5D9Eeq-c7imKJrgdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NtDxVJD9Eeq-c7imKJrgdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NtDxUZD9Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NtDxUpD9Eeq-c7imKJrgdQ" points="[-22, 8, -79, -77]$[-22, 53, -79, -32]$[56, 53, -1, -32]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NtE_cJD9Eeq-c7imKJrgdQ" id="(1.0,0.813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NtE_cZD9Eeq-c7imKJrgdQ" id="(0.006134969325153374,0.8641975308641975)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gU3Z8JD9Eeq-c7imKJrgdQ" type="4001" element="_gU2y4JD9Eeq-c7imKJrgdQ" source="_LRfGzJD9Eeq-c7imKJrgdQ" target="_bgtufJD9Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gU3Z85D9Eeq-c7imKJrgdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gU3Z9JD9Eeq-c7imKJrgdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gU3Z8ZD9Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gU3Z8pD9Eeq-c7imKJrgdQ" points="[0, 0, -164, 42]$[80, 0, -84, 42]$[80, -31, -84, 11]$[160, -31, -4, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gU4BAJD9Eeq-c7imKJrgdQ" id="(1.0,0.38271604938271603)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gU4BAZD9Eeq-c7imKJrgdQ" id="(0.02666666666666667,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_g7c405D9Eeq-c7imKJrgdQ" type="4001" element="_g7c40JD9Eeq-c7imKJrgdQ" source="_DQx_sJD9Eeq-c7imKJrgdQ" target="_bgtufJD9Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g7c41pD9Eeq-c7imKJrgdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g7c415D9Eeq-c7imKJrgdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g7c41JD9Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g7c41ZD9Eeq-c7imKJrgdQ" points="[0, -1, -251, -41]$[236, -1, -15, -41]$[236, 38, -15, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g7eG8JD9Eeq-c7imKJrgdQ" id="(1.0,0.5147058823529411)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g7eG8ZD9Eeq-c7imKJrgdQ" id="(0.4866666666666667,0.02666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0FAuM5D-Eeq-c7imKJrgdQ" type="4001" element="_0FAuMJD-Eeq-c7imKJrgdQ" source="_pDfhgJD-Eeq-c7imKJrgdQ" target="_vibT2JD-Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0FBVQpD-Eeq-c7imKJrgdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0FBVQ5D-Eeq-c7imKJrgdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0FBVQJD-Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0FBVQZD-Eeq-c7imKJrgdQ" points="[-2, -3, -15, 236]$[-2, -238, -15, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0FB8UJD-Eeq-c7imKJrgdQ" id="(0.5064935064935064,0.03896103896103896)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0FB8UZD-Eeq-c7imKJrgdQ" id="(0.6453900709219859,0.9857142857142858)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AWGFUJD_Eeq-c7imKJrgdQ" type="4001" element="_AWFeQJD_Eeq-c7imKJrgdQ" source="_vibT2JD-Eeq-c7imKJrgdQ" target="_61pUhJD-Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AWGFU5D_Eeq-c7imKJrgdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AWGFVJD_Eeq-c7imKJrgdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AWGFUZD_Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AWGFUpD_Eeq-c7imKJrgdQ" points="[0, 0, -127, -12]$[123, 11, -4, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AWGsYJD_Eeq-c7imKJrgdQ" id="(1.0,0.4714285714285714)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AWGsYZD_Eeq-c7imKJrgdQ" id="(0.11627906976744186,0.46511627906976744)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CkugEJD_Eeq-c7imKJrgdQ" type="4001" element="_Ckt5AJD_Eeq-c7imKJrgdQ" source="_61pUhJD-Eeq-c7imKJrgdQ" target="_BkZEeJD_Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CkugE5D_Eeq-c7imKJrgdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CkugFJD_Eeq-c7imKJrgdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CkugEZD_Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CkugEpD_Eeq-c7imKJrgdQ" points="[-22, -31, -144, 79]$[-22, -137, -144, -27]$[52, -137, -70, -27]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CkvuMJD_Eeq-c7imKJrgdQ" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CkvuMZD_Eeq-c7imKJrgdQ" id="(0.55,0.92)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IYIpIJD_Eeq-c7imKJrgdQ" type="4001" element="_IYE-wJD_Eeq-c7imKJrgdQ" source="_61pUhJD-Eeq-c7imKJrgdQ" target="_HYMPE5D_Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IYIpI5D_Eeq-c7imKJrgdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IYIpJJD_Eeq-c7imKJrgdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IYIpIZD_Eeq-c7imKJrgdQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IYIpIpD_Eeq-c7imKJrgdQ" points="[-10, 0, -155, 0]$[130, 0, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IYJ3QJD_Eeq-c7imKJrgdQ" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qLnxQqDjEeqzlurh4stdLQ" type="4001" element="_qLnKMKDjEeqzlurh4stdLQ" source="_oQdsIKDjEeqzlurh4stdLQ" target="_hjl--KD4Eeqfyd2IOtaQOQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qLoYUKDjEeqzlurh4stdLQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qLoYUaDjEeqzlurh4stdLQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qLnxQ6DjEeqzlurh4stdLQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qLnxRKDjEeqzlurh4stdLQ" points="[-22, -33, -157, 45]$[-22, -87, -157, -9]$[128, -87, -7, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qLo_YKDjEeqzlurh4stdLQ" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iqO24KD4Eeqfyd2IOtaQOQ" id="(0.04216867469879518,0.6024096385542169)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qxTRMqDjEeqzlurh4stdLQ" type="4001" element="_qxSqIKDjEeqzlurh4stdLQ" source="_oQdsIKDjEeqzlurh4stdLQ" target="_J65GgKGAEeq0NaN6XP5iqQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qxTRNaDjEeqzlurh4stdLQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qxTRNqDjEeqzlurh4stdLQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qxTRM6DjEeqzlurh4stdLQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qxTRNKDjEeqzlurh4stdLQ" points="[-22, 12, -159, -72]$[-22, 76, -159, -8]$[128, 76, -9, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qxVGYKDjEeqzlurh4stdLQ" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qxVGYaDjEeqzlurh4stdLQ" id="(0.04819277108433735,0.5783132530120482)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tBDtU6DjEeqzlurh4stdLQ" type="4001" element="_tBDtUKDjEeqzlurh4stdLQ" source="_hjl--KD4Eeqfyd2IOtaQOQ" target="_O753oKDjEeqzlurh4stdLQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tBEUYqDjEeqzlurh4stdLQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tBEUY6DjEeqzlurh4stdLQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tBEUYKDjEeqzlurh4stdLQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tBEUYaDjEeqzlurh4stdLQ" points="[0, 4, -102, -65]$[102, 4, 0, -65]$[102, 48, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tBE7cKDjEeqzlurh4stdLQ" id="(1.0,0.40963855421686746)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tgkT06DjEeqzlurh4stdLQ" type="4001" element="_tgkT0KDjEeqzlurh4stdLQ" source="_J65GgKGAEeq0NaN6XP5iqQ" target="_O753oKDjEeqzlurh4stdLQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tgk64KDjEeqzlurh4stdLQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tgk64aDjEeqzlurh4stdLQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tgkT1KDjEeqzlurh4stdLQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tgkT1aDjEeqzlurh4stdLQ" points="[0, 9, -65, 85]$[66, 9, 1, 85]$[66, -68, 1, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tgmJAKDjEeqzlurh4stdLQ" id="(1.0,0.40963855421686746)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tgmJAaDjEeqzlurh4stdLQ" id="(0.46511627906976744,0.813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uWsqkqDjEeqzlurh4stdLQ" type="4001" element="_uWsDgKDjEeqzlurh4stdLQ" source="_O753oKDjEeqzlurh4stdLQ" target="_pDfhgJD-Eeq-c7imKJrgdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uWtRoKDjEeqzlurh4stdLQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uWtRoaDjEeqzlurh4stdLQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uWsqk6DjEeqzlurh4stdLQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uWsqlKDjEeqzlurh4stdLQ" points="[-3, -12, -125, -1]$[109, -12, -13, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uWt4sKDjEeqzlurh4stdLQ" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uWt4saDjEeqzlurh4stdLQ" id="(0.08441558441558442,0.4805194805194805)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rdzqg6DmEeqzlurh4stdLQ" type="4001" element="_rdzqgKDmEeqzlurh4stdLQ" source="_bgtufJD9Eeq-c7imKJrgdQ" target="_oQdsIKDjEeqzlurh4stdLQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rdzqhqDmEeqzlurh4stdLQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rdzqh6DmEeqzlurh4stdLQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rdzqhKDmEeqzlurh4stdLQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rdzqhaDmEeqzlurh4stdLQ" points="[0, 0, -265, -334]$[51, 0, -214, -334]$[51, 334, -214, 0]$[244, 334, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rd04oKDmEeqzlurh4stdLQ" id="(1.0,0.3068181818181818)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Qp_IE6D5Eeqfyd2IOtaQOQ" type="4001" element="_Qp_IEKD5Eeqfyd2IOtaQOQ" source="_BkZEeJD_Eeq-c7imKJrgdQ" target="_Qp3zUKD5Eeqfyd2IOtaQOQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Qp_IFqD5Eeqfyd2IOtaQOQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Qp_IF6D5Eeqfyd2IOtaQOQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Qp_IFKD5Eeqfyd2IOtaQOQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Qp_IFaD5Eeqfyd2IOtaQOQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
